"""check string

Revision ID: 211d4c285453
Revises: 8d70cc243cb0
Create Date: 2025-04-22 14:38:21.836235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211d4c285453'
down_revision = '8d70cc243cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('track_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('track_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
