"""recrete storevist

Revision ID: 46631278e879
Revises: ccff19c7e5d2
Create Date: 2025-05-04 09:27:42.655107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46631278e879'
down_revision = 'ccff19c7e5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('visit_time', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_visit')
    # ### end Alembic commands ###
