"""added index

Revision ID: 73b3a0ce92ef
Revises: bbb9e2b98332
Create Date: 2025-05-11 16:33:48.588452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b3a0ce92ef'
down_revision = 'bbb9e2b98332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_initiator'), ['initiator'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_track_code'), ['track_code'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_slug'), ['slug'], unique=True)

    with op.batch_alter_table('store_visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_visit_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_visit_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_visit_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_shop_name'), ['shop_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_shop_name'))
        batch_op.drop_index(batch_op.f('ix_user_is_verified'))

    with op.batch_alter_table('store_visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_visit_user_id'))
        batch_op.drop_index(batch_op.f('ix_store_visit_session_id'))
        batch_op.drop_index(batch_op.f('ix_store_visit_seller_id'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_slug'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_track_code'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_initiator'))

    # ### end Alembic commands ###
