"""check table product for shelf

Revision ID: 9ff8c530d0ca
Revises: f6dffe7fd892
Create Date: 2025-02-14 17:27:37.397472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff8c530d0ca'
down_revision = 'f6dffe7fd892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('slug1')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('shelf')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug1', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
