"""add slug1

Revision ID: a5de2345c278
Revises: aea7c415b760
Create Date: 2025-02-15 14:43:57.276209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5de2345c278'
down_revision = 'aea7c415b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug1', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint("uq_user_slug1", ['slug1'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_slug1", type_='unique')
        batch_op.drop_column('slug1')

    # ### end Alembic commands ###
