"""added anonymous vistor logic

Revision ID: ac9bd2e8d063
Revises: dfe587443308
Create Date: 2025-05-04 08:52:10.298940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9bd2e8d063'
down_revision = 'dfe587443308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['visitor_id'], ['id'])
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
