"""check4

Revision ID: aea7c415b760
Revises: 4100717d3540
Create Date: 2025-02-15 14:29:51.916540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea7c415b760'
down_revision = '4100717d3540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug1', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['slug1'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug1')

    # ### end Alembic commands ###
