"""delete storevist

Revision ID: ccff19c7e5d2
Revises: ac9bd2e8d063
Create Date: 2025-05-04 09:26:42.557096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccff19c7e5d2'
down_revision = 'ac9bd2e8d063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_visit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('visitor_id', sa.INTEGER(), nullable=True),
    sa.Column('visit_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
