"""check for shop_theme

Revision ID: f5894e8e2906
Revises: f50821603b60
Create Date: 2025-04-18 11:02:19.208931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5894e8e2906'
down_revision = 'f50821603b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_theme', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shop_theme')

    # ### end Alembic commands ###
